notifications:
  slack: wsi-t113:SRHSOd3CgFDUwFxqv8SCXuIf
  email: false

sudo: false

language: ruby

services:
 - docker

script:
 - echo 'Build and check docker image'
 - docker build -t r-rnaseq .
 - docker images | grep -c r-rnaseq
 - echo 'Verify program(s) from this repo'
 - docker run -t --rm r-rnaseq R --version
 - docker run -t --rm r-rnaseq Rscript --version

